#!/usr/bin/env bash
# Select a config bundled with VIAME, or install and select a local config.
#
# Common usage:
#   bash setup_config.sh --list
#   bash setup_config.sh --show
#   bash setup_config.sh train_detector_rf_detr_l_seg_720.conf
#   bash setup_config.sh /path/to/custom_training.conf
#   bash setup_config.sh --project train_detector_rf_detr_l_720_90gb.conf

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/paths.sh"

usage() {
    cat <<'USAGE'
Usage:
  setup_config.sh --list
  setup_config.sh --show
  setup_config.sh CONFIG_NAME
  setup_config.sh --installed CONFIG_NAME
  setup_config.sh /path/to/local.conf
  setup_config.sh --project CONFIG_NAME_OR_PATH

CONFIG_NAME selects a config already present under the active VIAME
configs/pipelines directory.

A local path is copied into that directory and then selected. --project resolves
a basename relative to projects/viame_fish_2026/configs before copying it.
USAGE
}

show_selection() {
    echo "Selection state: $VF_CONFIG_SELECTION_FPATH"
    echo "Config name:     $VF_CONFIG_NAME"
    echo "Config path:     $VF_CONFIG_FPATH"
    if [ -f "$VF_CONFIG_FPATH" ]; then
        echo "Status:          present"
        sha256sum "$VF_CONFIG_FPATH"
    else
        echo "Status:          missing"
    fi
}

list_configs() {
    echo "Installed configs in $VF_CONFIG_DPATH"
    if [ -d "$VF_CONFIG_DPATH" ]; then
        find "$VF_CONFIG_DPATH" -maxdepth 1 -type f -name '*.conf' -printf '%f\n' | sort
    else
        echo "ERROR: active VIAME config directory is missing"
    fi

    echo
    echo "Project-owned configs in $VF_PROJECT_DPATH/configs"
    if [ -d "$VF_PROJECT_DPATH/configs" ]; then
        find "$VF_PROJECT_DPATH/configs" -maxdepth 1 -type f -name '*.conf' -printf '%f\n' | sort
    fi
}

if [ ! -f "$VF_CURRENT_VIAME_LINK/setup_viame.sh" ]; then
    echo "ERROR: active VIAME install is missing: $VF_CURRENT_VIAME_LINK"
    echo "Run setup_binaries.sh first."
    exit 1
fi

if [ "$1" = "--list" ]; then
    list_configs
    exit 0
fi

if [ "$1" = "--show" ]; then
    show_selection
    exit 0
fi

if [ -z "$1" ]; then
    show_selection
    echo
    usage
    echo
    list_configs
    exit 0
fi

MODE=auto
REQUEST="$1"

if [ "$1" = "--installed" ]; then
    MODE=installed
    REQUEST="$2"
fi

if [ "$1" = "--project" ]; then
    MODE=project
    REQUEST="$2"
fi

if [ -z "$REQUEST" ]; then
    usage
    exit 1
fi

mkdir -p "$VF_CONFIG_DPATH" "$VF_WORK_DPATH"

if [ "$MODE" = "project" ]; then
    if [ -f "$REQUEST" ]; then
        SOURCE_FPATH="$REQUEST"
    else
        SOURCE_FPATH="$VF_PROJECT_DPATH/configs/$REQUEST"
    fi

    if [ ! -f "$SOURCE_FPATH" ]; then
        echo "ERROR: project config does not exist: $SOURCE_FPATH"
        exit 1
    fi

    CONFIG_NAME="$(basename "$SOURCE_FPATH")"
    CONFIG_FPATH="$VF_CONFIG_DPATH/$CONFIG_NAME"
    cp -v "$SOURCE_FPATH" "$CONFIG_FPATH"
    CONFIG_ORIGIN="project-copy:$SOURCE_FPATH"
elif [ "$MODE" = "installed" ]; then
    CONFIG_NAME="$(basename "$REQUEST")"
    CONFIG_FPATH="$VF_CONFIG_DPATH/$CONFIG_NAME"
    CONFIG_ORIGIN="installed-viame"
elif [ -f "$REQUEST" ]; then
    SOURCE_FPATH="$REQUEST"
    CONFIG_NAME="$(basename "$SOURCE_FPATH")"
    CONFIG_FPATH="$VF_CONFIG_DPATH/$CONFIG_NAME"
    cp -v "$SOURCE_FPATH" "$CONFIG_FPATH"
    CONFIG_ORIGIN="local-copy:$SOURCE_FPATH"
else
    CONFIG_NAME="$(basename "$REQUEST")"
    CONFIG_FPATH="$VF_CONFIG_DPATH/$CONFIG_NAME"
    CONFIG_ORIGIN="installed-viame"
fi

if [ ! -f "$CONFIG_FPATH" ]; then
    echo "ERROR: selected config does not exist: $CONFIG_FPATH"
    echo
    list_configs
    exit 1
fi

{
    echo "# Generated by projects/viame_fish_2026/scripts/setup_config.sh"
    printf 'export VF_CONFIG_NAME=%q\n' "$CONFIG_NAME"
    printf 'export VF_CONFIG_ORIGIN=%q\n' "$CONFIG_ORIGIN"
    printf 'export VF_CONFIG_SELECTED_AT=%q\n' "$(date --iso-8601=seconds)"
} > "$VF_CONFIG_SELECTION_FPATH"

# Reload paths so the summary reflects the newly selected name.
unset VF_CONFIG_NAME VF_CONFIG_FPATH VF_CONFIG_ORIGIN VF_CONFIG_SELECTED_AT
source "$SCRIPT_DIR/paths.sh"

echo
echo "Selected VIAME training config"
echo "Name:   $VF_CONFIG_NAME"
echo "Path:   $VF_CONFIG_FPATH"
echo "Origin: ${VF_CONFIG_ORIGIN:-unknown}"
echo "State:  $VF_CONFIG_SELECTION_FPATH"
sha256sum "$VF_CONFIG_FPATH"

echo
echo "Important settings"
grep -nE 'downsample =|chip_(width|height|step_width|step_height|adaptive_thresh) =|image_reader:type|rf_detr:(segmentation|resolution|multi_scale|batch_size|max_epochs|val_subsample|ddp_timeout) =' "$VF_CONFIG_FPATH" || true
